mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

[footer]
since = 2_021

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "🔥"
subtitle = "Software Engineer"

[sidebar.avatar]
local = true
src = "avatar.png"

[article]
math = false

  [article.license]
  enabled = true
  default = "Licensed under CC BY-NC-SA 4.0"

[comments]
enabled = true
provider = "disqus"

  [comments.utterances]
  issueTerm = "pathname"

  [comments.remark42]

[widgets]
enabled = [ "search", "archives", "tag-cloud" ]

  [widgets.archives]
  limit = 5

  [widgets.tagCloud]
  limit = 10

[opengraph.twitter]
site = "mateusfccp"
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

